version: "3.9"
services:
    db:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        volumes:
            - ./pgdatatest:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
        container_name: database

    app:
        container_name: server
        restart: always
        build: .
        ports:
            - "3333:3333"
        depends_on:
            - db

        environment:
            - DB_HOST=db
        command: node -v
