version: "3"
services:
    db:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: orbita
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    app:
        container_name: server
        restart: always
        build: .
        ports:
            - "3333:3333"
        depends_on:
            - db
